version: "3"
services:
  nginx:
    container_name: nginx_proxy
    build:
      context: ./nginx
      dockerfile: ./
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/domain/dxts.conf:/etc/nginx/conf.d/dxts.conf
    ports:
      - "443:443"
    links:
      - api
    restart: on-failure
    networks:
      - dxtsOne

  api:
    container_name: api_container_node
    build:
      context: ./
      dockerfile: ./
    ports:
      - 3000:3000
    volumes:
      - ./package.json:/usr/src/app/package.json
      - ./:/usr/src/app
    env_file: .env
    restart: always
    links:
      - mysql
    networks:
      - dxtsOne

  mysql:
    container_name: mysql_container
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - ./mysql/vol:/var/lib/mysql
    env_file: ./mysql/.env-file
    restart: always
    networks:
      - dxtsOne
networks:
  dxtsOne:
    external: true
